### ISSUE TITLE
ModNet Configuration Has Invalid URI

### ISSUE THREAD

**Issue by DXPro25** [berkayylmao/setting-up-sbrw#2]
![Capture](https://user-images.githubusercontent.com/80214173/110889469-2c157b80-82bc-11eb-9d00-822efe17a2a9.PNG)

This code does not work:
{
 	"built_at": "2021-02-28T23:01:24.394847+03:00",
 	"entries": []
}

**Comment by 0P3N50URC3-F0R3V3R** [comment]
My problem that this code is works, but still not working the powerups and multiplayer part.
