### ISSUE TITLE
Thank you and Openfire version

### ISSUE THREAD

**Issue by cve-random** [berkayylmao/setting-up-sbrw#4]
Hello,

I just wanted to say thank you for making this awesome guide that works.
I also want to share that I had more luck with Openfire version 4.6.2. The version in the original repo had a wrong version of the JAXB-API and didn't want to work.

Thanks again.

**Comment by Pixela8** [comment]
Hey! I'm using the latest version but 4.6.2 works perfectly for run a SBRW server?
