### ISSUE TITLE
No powerups, multiplayer, etc Even with ModNet setup

### ISSUE THREAD

**Issue by cve-random** [berkayylmao/setting-up-sbrw#5]
Hello.

I just have no error, no logs, afaik, I have no info. I have checked if the HTTP server can be accessed and it is with the index.json no problem

Thank you for your suggestions

**Comment by sakvarelidze** [comment]
@cve-random Hello, may I ask you how did you set up the ModNet ? I want to do the same thing and double-check whether I'll pop into a same issue

**Comment by cve-random** [comment]
```json
{ 	
    "built_at": "2021-02-28T23:01:24.394847+03:00", 	
    "entries": [] 
}
```
But it may also be Openfire that is the issue. This is what I had at least :)

**Comment by sakvarelidze** [comment]
have you added the necessary rows to the Parameter Table?
``
MODDING_BASE_PATH (value: same as SERVER_ADDRESS), 
MODDING_ENABLED (value: true), 
MODDING_FEATURES (value: ""), 
MODDING_SERVER_ID (value: a unique name for your server, it won't be visible to the public) 
``

**Comment by cve-random** [comment]
I also added them. I will clarify that this issue was solved 2 weeks ago. Sorry for the confusion.
NB: If it helps anybody, I have solved this issue by using  the SBRW fork of Openfire and not the official fork.
